ui: tape
browserify:
  - transform:
      name: babelify
      presets: [["@babel/preset-env", { "targets": { "browsers": "last 1 chrome version" } }]]
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: opera
    version: latest
  - name: safari
    version: latest
  - name: iphone
    version: latest
