export const ADD_ICE_CANDIDATE = 'ERR_ADD_ICE_CANDIDATE'

export const CREATE_ANSWER = 'ERR_CREATE_ANSWER'

export const CREATE_OFFER = 'ERR_CREATE_OFFER'

export const DATA_CHANNEL = 'ERR_DATA_CHANNEL'

export const ICE_CONNECTION_CLOSED = 'ERR_ICE_CONNECTION_CLOSED'

export const ICE_CONNECTION_FAILURE = 'ERR_ICE_CONNECTION_FAILURE'

export const PEER_IS_DESTROYED = 'ERR_PEER_IS_DESTROYED'

export const REMOVE_TRACK = 'ERR_REMOVE_TRACK'

export const SET_LOCAL_DESCRIPTION = 'ERR_SET_LOCAL_DESCRIPTION'

export const SET_REMOTE_DESCRIPTION = 'ERR_SET_REMOTE_DESCRIPTION'

export const SIGNALING = 'ERR_SIGNALING'

export const WEBRTC_SUPPORT = 'ERR_WEBRTC_SUPPORT'
